FROM php:8.2-cli

# Composer (gestionnaire PHP)
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .

# Dépendances PHP (Stripe)
RUN composer install --no-dev --prefer-dist

# Port fourni par Render
ENV PORT=10000
CMD ["sh", "-c", "php -S 0.0.0.0:${PORT}"]
